[workspace]
members = [
    "meta-vote-contract",
    "kv-store-contract",
    "mpip-contract",
    "test-meta-token",
    "near-workspaces-integration-test"
]
resolver = "2"

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true